Statechanger feature
expl0r3rgu1/floppy-floppa pull request #102
Opened 2022-04-07 20:17 UTC by ValentinaPieri

2022-04-07 23:11 UTC, expl0r3rgu1 requested changes

2022-04-07 23:11 UTC, expl0r3rgu1 commented on src/main/state_changers/StateChanger.java
> +	Skin skin;
Make this private

2022-04-08 15:09 UTC, benedettapacilli approved these changes

2022-04-08 15:53 UTC, criicchio approved these changes

2022-04-09 08:50 UTC, expl0r3rgu1 approved these changes

2022-04-09 08:50 UTC, merged