Replaced this.position with getPosition and setPosition
expl0r3rgu1/floppy-floppa pull request #104
Opened 2022-04-08 07:14 UTC by benedettapacilli

2022-04-08 07:20 UTC, expl0r3rgu1 requested changes

2022-04-08 07:20 UTC, expl0r3rgu1 commented on src/main/obstacles/MovingObstacle.java
> +		setPosition(((int) SIZE.getWidth()) + 1, ((int) SIZE.getHeight()) / 2);
Remove this line

2022-04-09 11:47 UTC, criicchio approved these changes

2022-04-09 12:55 UTC, expl0r3rgu1 approved these changes

2022-04-10 16:05 UTC, ValentinaPieri approved these changes

2022-04-10 16:05 UTC, merged