Shop hotfix
expl0r3rgu1/floppy-floppa pull request #202
Opened 2022-04-17 21:51 UTC by benedettapacilli

Shop wasn't showing

2022-04-18 08:02 UTC, expl0r3rgu1 approved these changes

2022-04-18 09:35 UTC, expl0r3rgu1 requested changes
Missing this assignment:
```java
background = CommonMethods.getImageResource("Background");
```

2022-04-18 16:44 UTC, criicchio approved these changes

2022-04-18 22:12 UTC, ValentinaPieri approved these changes

2022-04-18 22:27 UTC, expl0r3rgu1 submitted a review, later dismissed

2022-04-19 16:03 UTC, expl0r3rgu1 approved these changes

2022-04-19 16:03 UTC, merged