Update obstacle enhancement
expl0r3rgu1/floppy-floppa pull request #226
Opened 2022-04-19 21:08 UTC by ValentinaPieri

2022-04-19 21:19 UTC, criicchio approved these changes

2022-04-19 22:00 UTC, benedettapacilli approved these changes

2022-04-20 11:53 UTC, expl0r3rgu1 requested changes
Move space constant in Constants class

2022-04-20 12:02 UTC, expl0r3rgu1 requested changes
Issue #237 needs to be fixed

2022-04-20 13:59 UTC, expl0r3rgu1 approved these changes

2022-04-20 13:59 UTC, merged