Booster junit ehnancement
expl0r3rgu1/floppy-floppa pull request #232
Opened 2022-04-19 23:17 UTC by benedettapacilli

2022-04-19 23:22 UTC, criicchio approved these changes

2022-04-20 09:33 UTC, ValentinaPieri approved these changes

2022-04-20 11:35 UTC, expl0r3rgu1 requested changes

2022-04-20 11:35 UTC, expl0r3rgu1 commented on src/junit/TestCoinsIncrement.java
> +		assertTrue(coinsIncrement.changeState() >= 0 && coinsIncrement.changeState() <= 100);
Use a for loop

2022-04-20 11:40 UTC, expl0r3rgu1 approved these changes

2022-04-20 11:40 UTC, merged