Added MainMenu field
expl0r3rgu1/floppy-floppa pull request #91
Opened 2022-04-06 19:41 UTC by benedettapacilli

Closes #89

2022-04-06 19:42 UTC, criicchio approved these changes

2022-04-06 19:52 UTC, expl0r3rgu1 requested changes
The MainMenu field is still missing. Only its method has been called in the button ActionListener.

2022-04-06 20:54 UTC, criicchio approved these changes

2022-04-06 21:06 UTC, criicchio approved these changes

2022-04-07 07:33 UTC, ValentinaPieri approved these changes

2022-04-07 09:19 UTC, expl0r3rgu1 approved these changes

2022-04-07 09:19 UTC, merged