Added missing mainMenu field
expl0r3rgu1/floppy-floppa pull request #92
Opened 2022-04-06 19:46 UTC by benedettapacilli

Closes #90

2022-04-06 19:56 UTC, expl0r3rgu1 requested changes
The MainMenu field is still missing. Only its method has been called in the button ActionListener.

2022-04-06 20:56 UTC, criicchio approved these changes

2022-04-06 21:06 UTC, criicchio approved these changes

2022-04-07 07:36 UTC, ValentinaPieri approved these changes

2022-04-07 10:11 UTC, expl0r3rgu1 approved these changes

2022-04-07 10:11 UTC, merged